import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'vinay',
      email: 'vinay@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'hr',
      email: 'hr@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    }
  ],
  products: [
    {
      //_id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt', // slug is used to generate the url
      category: 'Shirts',
      image: '/images/p1.jpg', //Dimension of all images are 679px X 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      //_id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 15,
      brand: 'Puma',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '5',
      name: 'watch',
      slug: 'watch',
      category: 'watch',
      image: '/images/p5.jpg',
      price: 50,
      countInStock: 15,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '6',
      name: 'shoes',
      slug: 'shoes',
      category: 'shoe',
      image: '/images/p6.jpg',
      price: 45,
      countInStock: 15,
      brand: 'puma',
      rating: 3.9,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '7',
      name: 'goggles',
      slug: 'sunglasses',
      category: 'sunglasses',
      image: '/images/p7.jpg',
      price: 35,
      countInStock: 15,
      brand: 'levis',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '7',
      "name": "Perfumes",
      "slug": "Perfumes",
      "category": "Perfumes",
      "image": '/images/p8.jpg',
      "price": 50,
      "countInStock": 15,
      "brand": "fogg",
      "rating": 4.5,
      "numReviews": 10,
      "description": 'high quality product',
    },
    {
      //_id: '7',
      "name": "Earphones",
      "slug": "Earphones",
      "category": "Earphones",
      "image": "/images/p9.jpg",
      "price": 25,
      "countInStock": 15,
      "brand": "Telex",
      "rating": 3.9,
      "numReviews": 10,
      "description": "avg quality product",
    },
    {
      //_id: '7',
      "name": "toys",
      "slug": "car toy for kids",
      "category": "car toy",
      "image": "/images/p10.jpg",
      "price": 50,
      "countInStock": 15,
      "brand": "Hot Wheel",
      "rating": 4.7,
      "numReviews": 10,
      "description": "high quality product",
    },
  ],
};
export default data;
